### PR TITLE
Get formats

### PR DESCRIPTION
**Pull request by julianfbeck**
Generate Buttons to select the download function

### CODE REVIEW

**Comment by julianfbeck** [comment]
image

**Comment by julianfbeck** [comment]
@begginer-123 Nice, do you want to add it in the next pr?

**Comment by iamLiquidX** [comment]
> @begginer-123 Nice, do you want to add it in the next pr?

no i just gave u suggestions so that you can make the improvements prior to launch. otherwise you are gonna rework on this.

**Comment by julianfbeck** [comment]
> > @begginer-123 Nice, do you want to add it in the next pr?
> 
> no i just gave u suggestions so that you can make the improvements prior to launch. otherwise you are gonna rework on this.

Well this is not how this platform is supposed to work....
 
Anyway, i don't think it's necessary to cluster by audio or video. When you choose to select the format you already know what you want. Most of the time you would just select download video or audio in the bot and yt-dl selects the best audio or video automatically.

**Comment by iamLiquidX** [comment]
> > > @begginer-123 Nice, do you want to add it in the next pr?
> > 
> > 
> > no i just gave u suggestions so that you can make the improvements prior to launch. otherwise you are gonna rework on this.
> 
> Well this is not how this platform is supposed to work....
> 
> Anyway, i don't think it's necessary to cluster by audio or video. When you choose to select the format you already know what you want. Most of the time you would just select download video or audio in the bot and yt-dl selects the best audio or video automatically.

my sincere apologies. i just started on this platform and programming. i will keep your words in mind

**Comment by julianfbeck** [comment]
@begginer-123 No worries, keep on learning 👍

**Pull request merged**
